---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
        server {
            root /usr/share/nginx/html;

            location / {
                autoindex   on;
                sendfile    on;
                sendfile_max_chunk  1m;
            }

            location /assets/ {
                autoindex   on;
                sendfile    on;
                sendfile_max_chunk  1m;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          optional: true
      - name: sensu-asset-server-ca-cert
        secret:
          secretName: sensu-asset-server-ca-cert
          defaultMode: 256
          optional: true
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - protocol: TCP
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      - name: sensu-agent
        image: sensu/sensu:6.7.2
        command: [
          "/opt/sensu/bin/sensu-agent", "start",
          "--detect-cloud-provider", "true",
          "--log-level", "warn",
        ]
        env:
        - name: KUBE_NAMESPACE # Kubernetes namespace where Sensu backend is deployed
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SENSU_BACKEND_URL
          value: "ws://sensu-backend-0.sensu.$(KUBE_NAMESPACE).svc.cluster.local:8081 ws://sensu-backend-1.sensu.$(KUBE_NAMESPACE).svc.cluster.local:8081 ws://sensu-backend-2.sensu.$(KUBE_NAMESPACE).svc.cluster.local:8081"
        - name: SENSU_NAMESPACE
          value: "$(KUBE_NAMESPACE)"
        - name: SENSU_SUBSCRIPTIONS
          value: "sensu-backend kubernetes"
        - name: SENSU_KEEPALIVE_INTERVAL
          value: "5"
        - name: SENSU_KEEPALIVE_WARNING_TIMEOUT
          value: "10"
        - name: SENSU_DEREGISTER
          value: "true"
        - name: SENSU_DEREGISTRATION_HANDLER
          value: "deregister"
        - name: SENSU_API_HOST
          value: "127.0.0.1"
        - name: SENSU_API_PORT
          value: "3031"
        - name: SENSU_STATSD_METRICS_HOST
          value: "127.0.0.1"
        - name: SENSU_STATSD_METRICS_PORT
          value: "8125"
        - name: SENSU_STATSD_FLUSH_INTERVAL
          value: "10"
        - name: SENSU_STATSD_EVENT_HANDLERS
          value: "statsd"
        volumeMounts: []
        ports: []
